batchSize: 4
length: 256
epochs: 10
stepsPerEpoch: 128

printFrequency: 10
saveFrequency: 10

samplesDir: './samples'
weightsDir: './checkpoints'

learningRate: 0.0004
checkpoints: False

noDecom: False