batchSize: 2
length: 256
epochs: 1
stepsPerEpoch: 128

printFrequency: 10
saveFrequency: 1

weightsDir: '../weights/supernet/checkpoint-latest.pth'

learningRate: 0.0004
checkpoints: False

choiceNum: 8
choiceLayer: 8